library(rvest)
library(dplyr)
library(stringr)
library(robotstxt)
url <- 'https://www.imdb.com/list/ls055386972/'
web <- read_html(url)
View(web)
name <- web %>% html_nodes('.lister-item-header a') %>% html_text()
View(name)
reting <- web %>% html_nodes('.ipl-rating-star.small .ipl-rating-star__rating') %>% html_text()
View(reting)
dur_time <- web %>% html_nodes('.runtime') %>% html_text()
View(dur_time)
gen_re <- web %>% html_nodes('.genre') %>% html_text()
View(gen_re)
movie = data.frame(name,reting,dur_time,gen_re)
View(movie)
write.csv(movie,"ImdbTOP50 MOVIE.csv")
str(movie)
